# -*- coding: utf-8 -*-
"""Object oriented programming 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fpj_NC7sQChFID1VLBkenvPc3Q4b0ivz
"""

L=[2,3,4,5]
L.append(6)
print(L)

L=[2,3,4,5]
print(type(L))

# This is a syntax to create an object
object_name = class_name()

L=list()# esme list ek class hai aur L is a object hai
L

s=str()# yaha str is a class but s is a object
s

# Pascal case
#Kabhi bhi class ko banate hai to pascal case jese lekhte hai
HelloWorld

# yani hr starting word capital letter se hoga.

# Write a program to create a Atm software

class MyAtm:

  # Variable do cheia pin aur baleance to uske liye constructor cheia
  #constructor is a special function which dont need for call the function
  # Eske under ek super power hota hai
  def __init__(self): # ye constructor hai
    self.pin =''
    self.balance =0
    print('mai to execute ho gye re mere bhai')
    self.menu()

#Note:- Jetne baar es constructor ka object baniyenge utne baar automatic call ho jyega
  #Ab hub kuch functionality add krenge so create function
  def menu(self):
   user_input= input("""
    Hi! How can i help you.
    1.Press 1 to create pin.
    2. Press 2 to change pin
    3. Press 3 to cheak baleance.
    4. Press 4 to withdraw.
    5. Anything else to exit.
    """)
   if user_input=='1':
    #Create pin
    self.create_pin()
   elif user_input=='2':
    #Change pin
    self.change_pin()

   elif user_input=='3':
    #Cheak baleance
    self.cheak_baleance()


   elif user_input=='4':
    #Withdrowl amount
    self.withdrawl()

   else:
    exit()


  def create_pin(self): # This place we create pin function.
     user_pin=input('Enter your pin.')
     self.pin=user_pin

     user_balance=input('Enter your baleance.')
     self.balance=user_balance

     print('Pin created successfully.')
     self.menu()# for continuity the program

  def change_pin(self):
   old_pin=input('Enter your old pin.')
   if old_pin==self.pin:
    #let him change the pin
    new_pin=input('Enter the new pin.')
    self.pin=new_pin
    print('Your pin change successfully.')
    self.menu()# for continuity the program
   else:
    print('Sorry yaar you can not change the pin.')
    self.menu()# for continuity the program

  def cheak_baleance(self):
    user_pin=input('Enter your pin.')
    if user_pin==self.pin:
      print('Your balance is=',self.balance)
    else:
      print('chal nekal yaha se ghoote.')
      self.menu()# for continuity the program


  def withdrawl(self):
    user_pin=input('Enter the pin')
    if user_pin==self.pin:
      #allow to withdrowl
      amount=int(input('Enter the amount'))
      if amount <= self.balance:
        self.balance=self.balance-amount
        print('Withdrawl Successfully baleance is=',self.balance)
      else:
        print('Abe Garib sale  kuch to saram kro')


       # print('Can you want to reciept the withdrawl')
      #  user_pin=input('Enter the pin')
       # if user_pin==self.pin:
       #   print('Take your recipt')
      #  else:
      #    print('Sorry your pin is incorrect')

    else:
      print('Sale chor bhag nhi to police ko call kr dunga')

      self.menu()

# write object code of my atm
obj=MyAtm()

# Differance between function and methods
L=[1,2,3,4,5]
len(L) # it is a function because it is outsideof the list class
L.append(6)#it is a methods because it is inside the list calass

print(type(obj))

obj2=MyAtm()